version: '3.7'
services:
  app:
    build: .
    environment:
      - PORT=8424
      - JWT_SECRET=secret
      - TYPEORM_CONNECTION=mongodb
      - TYPEORM_HOST=mongodb
      - TYPEORM_PORT=27017
      - TYPEORM_DATABASE=goopi
    ports:
      - '8424:8424'
    links:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:latest
    ports:
      - '27021:27017'
    networks:
      - internal

networks:
  internal:
    driver: bridge
